name: CodeCov CI Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run curl to codecov
      run: curl -s https://codecov.io/bash -t c4e13a83-e8dd-4509-860c-9932160da3c8
